namespace PassiveBOT.strings
{
    public class FunStr
    {
        //8ball
        public static string[] Answers =
        {
            "It is certain",
            "It is decidedly so",
            "Without a doubt",
            "Yes definitely",
            "You may rely on it",
            "As I see it, yes",
            "Most likely",
            "Outlook good",
            "Yes",
            "Signs point to yes",
            "Reply hazy try again",
            "Ask again later",
            "Better not tell you now",
            "Cannot predict now",
            "Concentrate and ask again",
            "Don't count on it",
            "My reply is no",
            "My sources say no",
            "Outlook not so good",
            "Very doubtful"
        };

        //dick
        public static string[] Dick =
        {
            "8=D boy you got some growing to do",
            "8===================================D damn you a bit boy :wink:",
            "ERROR: DICK TOO SMALL",
            "ERROR: Too Big to send",
            "8===================================================D:sweat_drops:",
            "8=========D~~~ wow you're fast",
            "8===========================D not bad",
            "({}) you a pussy bitch",
            "8================D",
            "8D Bruh wheres your shaft at",
            "8-----------D skinny fucker"
        };

        //insult
        public static string[] Insult =
        {
            "Shut up, you'll never be the man your mother is.",
            "You're a failed abortion whose birth certificate is an apology from the condom factory.",
            "You must have been born on a highway, because that's where most accidents happen.",
            "Your family tree is a cactus, because everybody on it is a prick.",
            "You're so ugly Hello Kitty said goodbye to you.",
            "It looks like your face caught on fire and someone tried to put it out with a fork.",
            "You are so ugly that when your mama dropped you off at school she got a fine for littering.",
            "If you were twice as smart, you'd still be stupid.",
            "Do you have to leave so soon? I was just about to poison the tea.",
            "Your so ugly when you popped out the doctor said aww what a treasure and your mom said yeah lets bury it",
            "Dumbass.",
            "We all sprang from apes, but you didn't spring far enough.",
            "I hear when you were a child your mother wanted to hire somebody to take care of you, but the mafia wanted too much.",
            "Out of 100,000 sperm, you were the fastest?",
            "If you really want to know about mistakes, you should ask your parents.",
            "Hey, you have something on your chin...3rd one down.",
            "When you were born, the police arrested your dad, the doctor slapped your mom, animal control euthanized your brother, and A&E made a documentary that saved your life.",
            "I'm not saying I hate you, but I would unplug your life support to charge my phone.",
            "Is your ass jealous of the amount of shit that just came out of your mouth?",
            "Roses are red, violets are blue, I have 5 fingers, the 3rd ones for you.",
            "You're the reason they invented double doors!",
            "I wasn't born with enough middle fingers to let you know how I feel about you.",
            "You bring everyone a lot of joy, when you leave the room.",
            "I bet your brain feels as good as new, seeing that you never use it.",
            "If you are going to be two faced, at least make one of them pretty.",
            "If laughter is the best medicine, your face must be curing the world.",
            "What's the difference between you and eggs? Eggs get laid and you don't.",
            "I'm jealous of all the people that haven't met you!",
            "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
            "I could eat a bowl of alphabet soup and shit out a smarter statement than that.",
            "Two wrongs don't make a right, take your parents as an example.",
            "There's only one problem with your face, I can see it.",
            "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
            "You're so ugly you scare the shit back into people.",
            "You shouldn't play hide and seek, no one would look for you.",
            "I don't exactly hate you, but if you were on fire and I had water, I'd drink it."
        };

        //dice
        public static string[] Dice =
        {
            "https://www.wpclipart.com/recreation/games/dice/die_face_1.png",
            "https://www.wpclipart.com/recreation/games/dice/die_face_2.png",
            "https://www.wpclipart.com/recreation/games/dice/die_face_3.png",
            "https://www.wpclipart.com/recreation/games/dice/die_face_4.png",
            "https://www.wpclipart.com/recreation/games/dice/die_face_5.png",
            "https://www.wpclipart.com/recreation/games/dice/die_face_6.png"
        };

        //fortune
        public static string[] Fortune =
        {
            "Today it's up to you to create the peacefulness you long for.",
            "A friend asks only for your time not your money.",
            "If you refuse to accept anything but the best, you very often get it.",
            "A smile is your passport into the hearts of others.",
            "A good way to keep healthy is to eat more Chinese food.",
            "Your high-minded principles spell success.",
            "Hard work pays off in the future, laziness pays off now.",
            "Change can hurt, but it leads a path to something better.",
            "Enjoy the good luck a companion brings you.",
            "People are naturally attracted to you.",
            "Hidden in a valley beside an open stream- This will be the type of place where you will find your dream.",
            "A chance meeting opens new doors to success and friendship.",
            "You learn from your mistakes... You will learn a lot today.",
            "If you have something good in your life, don't let it go!",
            "What ever you're goal is in life, embrace it visualize it, and for it will be yours.",
            "Your shoes will make you happy today.",
            "You cannot love life until you live the life you love.",
            "Be on the lookout for coming events; They cast their shadows beforehand.",
            "Land is always on the mind of a flying bird.",
            "The man or woman you desire feels the same about you.",
            "Meeting adversity well is the source of your strength.",
            "A dream you have will come true.",
            "Our deeds determine us, as much as we determine our deeds.",
            "Never give up. You're not a failure if you don't give up.",
            "You will become great if you believe in yourself.",
            "There is no greater pleasure than seeing your loved ones prosper.",
            "You will marry your lover.",
            "A very attractive person has a message for you.",
            "You already know the answer to the questions lingering inside your head.",
            "It is now, and in this world, that we must live.",
            "You must try, or hate yourself for not trying.",
            "You can make your own happiness.",
            "The greatest risk is not taking one.",
            "The love of your life is stepping into your planet this summer.",
            "Love can last a lifetime, if you want it to.",
            "Adversity is the parent of virtue.",
            "Serious trouble will bypass you.",
            "A short stranger will soon enter your life with blessings to share.",
            "Now is the time to try something new.",
            "Wealth awaits you very soon.",
            "If you feel you are right, stand firmly by your convictions.",
            "If winter comes, can spring be far behind?",
            "Keep your eye out for someone special.",
            "You are very talented in many ways.",
            "A stranger, is a friend you have not spoken to yet.",
            "A new voyage will fill your life with untold memories.",
            "You will travel to many exotic places in your lifetime.",
            "Your ability for accomplishment will follow with success.",
            "Nothing astonishes men so much as common sense and plain dealing.",
            "Its amazing how much good you can do if you dont care who gets the credit.",
            "Everyone agrees. You are the best.",
            "LIFE CONSIST NOT IN HOLDING GOOD CARDS, BUT IN PLAYING THOSE YOU HOLD WELL.",
            "Jealousy doesn't open doors, it closes them!",
            "It's better to be alone sometimes.",
            "When fear hurts you, conquer it and defeat it!",
            "Let the deeds speak.",
            "You will be called in to fulfill a position of high honor and responsibility.",
            "The man on the top of the mountain did not fall there.",
            "You will conquer obstacles to achieve success.",
            "Joys are often the shadows, cast by sorrows.",
            "Fortune favors the brave.",
            "An upward movement initiated in time can counteract fate.",
            "A journey of a thousand miles begins with a single step.",
            "Sometimes you just need to lay on the floor.",
            "Never give up. Always find a reason to keep trying.",
            "If you have something worth fighting for, then fight for it.",
            "Stop wishing. Start doing.",
            "Accept your past without regrets. Handle your present with confidence. Face your future without fear.",
            "Stay true to those who would do the same for you.",
            "Ask yourself if what you are doing today is getting you closer to where you want to be tomorrow.",
            "Happiness is an activity.",
            "Help is always needed but not always appreciated. Stay true to your heart and help those in need weather they appreciate it or not.",
            "Hone your competitive instincts.",
            "Finish your work on hand don't be greedy.",
            "For success today, look first to yourself.",
            "Your fortune is as sweet as a cookie.",
            "Integrity is the essence of everything successful.",
            "If you're happy, you're successful.",
            "You will always be surrounded by true friends",
            "Believing that you are beautiful will make you appear beautiful to others around you.",
            "Happinees comes from a good life.",
            "Before trying to please others think of what makes you happy.",
            "When hungry, order more Chinese food.",
            "Your golden opportunity is coming shortly.",
            "For hate is never conquered by hate. Hate is conquered by love .",
            "You will make many changes before settling down happily.",
            "A man is born to live and not prepare to live.",
            "You cannot become rich except by enriching others.",
            "Don't pursue happiness - create it.",
            "You will be successful in love.",
            "All your fingers can't be of the same length.",
            "Wise sayings often fall on barren ground, but a kind word is never thrown away.",
            "A lifetime of happiness is in store for you.",
            "It is very possible that you will achieve greatness in your lifetime.",
            "Be tactful; overlook your own opportunity.",
            "You are the controller of your destiny.",
            "Everything happens for a reson.",
            "How can you have a beutiful ending without making beautiful mistakes.",
            "You can open doors with your charm and patience.",
            "Welcome the change coming into your life."
        };
    }
}